#!/bin/bash

#Downloads newest discord .deb installation and installs it if current is outdated
CUR_VER=$(dpkg-query -W -f='${Version}' "discord")

#the flag --content-disposition used to get a properly named file instead of the the GET parameters as name
wget --content-disposition 'https://discordapp.com/api/download/stable?platform=linux&format=deb'

DSC_PATH=$(find . -name "discord*.deb")

NEW_VER=$(basename "$DSC_PATH" | sed -n 's/^[^-]*-\([^-]*\)\.deb$/\1/p')
if [ -z "$NEW_VER" ]; then
        echo "Failed to get Version from: $DSC_PATH"
	echo "Check  file name"
	exit 1
fi

if dpkg --compare-versions "$CUR_VER" "lt" "$NEW_VER"; then
        echo "Proceeding to install discord-$NEW_VER.deb given version $CUR_VER"
else
        echo "Current Version $CUR_VER is newer than or equal to downloaded .deb: $NEW_VER"
        echo "Deleting $DSC_PATH"
	rm "$DSC_PATH"
	exit 1
fi
sudo dpkg -i "$DSC_PATH"
rm "$DSC_PATH"
